openapi: 3.1.0
info:
  title: Environments.v2
  version: '1.0'
  description: Retrieve environments information via a GET request.
servers:
  - url: 'http://localhost:3000'
paths:
  /environment/:
    parameters:
      - schema:
          type: integer
        name: dsl
        in: query
        required: false
        description: Dataset Layer ID
    get:
      summary: Get Environment Info
      tags: []
      responses:
        '200':
          description: Environment Found
          content:
            application/json:
              examples:
                $ref:
                  value:
                    Environment:
                      DSL:
                        ID: 1
                        status_map:
                          '0':
                            title: NO DATA
                            style: '#333'
                          '1':
                            title: NO LOCKDOWN
                            style: '#93c47d'
                          '2':
                            title: PARTIAL LOCKDOWN
                            style: '#f6b26b'
                        overlay:
                          tabs:
                            - title: Daily Life
                              react_component: ....
                              key_values:
                                population: Population
                                maximum_assembly: Maximum assembly
                                daily_life: Daily life (restrictions)
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    Environment:
                      DSL:
                        ID: 1
                        status_map:
                          '0':
                            title: NO DATA
                            style: '#333'
                          '1':
                            title: NO LOCKDOWN
                            style: '#93c47d'
                          '2':
                            title: PARTIAL LOCKDOWN
                            style: '#f6b26b'
                        overlay:
                          tabs:
                            - title: Daily Life
                              react_component: ....
                              key_values:
                                population: Population
                                maximum_assembly: Maximum assembly
                                daily_life: Daily life (restrictions)
            application/xml:
              schema:
                type: object
                properties:
                  '':
                    type: string
        '404':
          description: Environment Not Found
      operationId: get-users-userId
      description: Retrieve environments information via a GET request.
components:
  schemas: {}
